name: Build and Deploy Backend and Frontend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    permissions:
      contents: read
    name: Build and Deploy to Azure App Service
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Clear node_modules
        run: rm -rf node_modules

      - name: Install backend dependencies
        run: npm install --production
        working-directory: .

      - name: Build Next.js app (Frontend)
        run: npm run build
        working-directory: .
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
          NEXT_PUBLIC_GOOGLE_AUTH_URL: ${{ secrets.NEXT_PUBLIC_GOOGLE_AUTH_URL }}

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            .
            !./node_modules  # Exclude node_modules to avoid duplication

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'greenthicks-backend'
          slot-name: 'Production'
          package: .

  close-pull-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    permissions:
      id-token: write
      contents: read
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'greenthicks-backend'
          slot-name: 'Production'
          action: 'close'
